import type {
  PaymentCategory,
  ExtendedPaymentStatus,
  CompanyPaymentItem,
} from "../lib/interfaces";

export type { PaymentCategory, ExtendedPaymentStatus, CompanyPaymentItem };

const SEED_COMPANY_PAYMENTS: CompanyPaymentItem[] = [
  {
    id: 1,
    reference: "PF-PAY-904121",
    batchId: "BATCH-2026-SEP-01",
    companyId: 101,
    companyName: "Acme Technologies Ltd",
    companyEmail: "finance@acmetech.io",
    employeeName: "Deji Doess",
    employeeEmail: "deji.doess@acmetech.io",
    employeeRole: "Senior Frontend Engineer",
    department: "Engineering",
    bankName: "Guaranty Trust Bank (GTBank)",
    accountNumber: "0128938471",
    accountName: "Deji Doess",
    amount: 650000,
    fee: 50,
    netAmount: 650000,
    paymentType: "Salary",
    status: "successful",
    date: "2026-09-24T11:20:00",
    narration: "September 2026 Staff Salary Disbursal",
    approvedBy: "Finance Clearance Desk",
    approvedAt: "2026-09-24T11:22:15",
    gatewayRef: "GTB-TRF-882710491",
  },
  {
    id: 2,
    reference: "PF-PAY-904122",
    batchId: "BATCH-2026-SEP-01",
    companyId: 101,
    companyName: "Acme Technologies Ltd",
    companyEmail: "finance@acmetech.io",
    employeeName: "Adaeze Nwosu",
    employeeEmail: "adaeze.nwosu@acmetech.io",
    employeeRole: "Lead Product Designer",
    department: "Product Design",
    bankName: "Access Bank",
    accountNumber: "0719827364",
    accountName: "Adaeze Nwosu",
    amount: 580000,
    fee: 50,
    netAmount: 580000,
    paymentType: "Salary",
    status: "successful",
    date: "2026-09-24T11:20:00",
    narration: "September 2026 Staff Salary Disbursal",
    approvedBy: "Finance Clearance Desk",
    approvedAt: "2026-09-24T11:22:18",
    gatewayRef: "ACC-TRF-991827364",
  },
  {
    id: 3,
    reference: "PF-PAY-904123",
    batchId: "BATCH-2026-SEP-02",
    companyId: 102,
    companyName: "Sunmence Tech Limited",
    companyEmail: "company@payfleet.io",
    employeeName: "Tunde Bakare",
    employeeEmail: "tunde.bakare@sunmence.com",
    employeeRole: "DevOps & Infrastructure Lead",
    department: "Engineering",
    bankName: "Zenith Bank",
    accountNumber: "2081928374",
    accountName: "Tunde Bakare",
    amount: 720000,
    fee: 50,
    netAmount: 720000,
    paymentType: "Salary",
    status: "pending",
    date: "2026-09-24T14:45:00",
    narration: "September Salary Disbursal",
  },
  {
    id: 4,
    reference: "PF-PAY-904124",
    batchId: "BATCH-2026-SEP-02",
    companyId: 102,
    companyName: "Sunmence Tech Limited",
    companyEmail: "company@payfleet.io",
    employeeName: "Grace Adeyemi",
    employeeEmail: "grace.adeyemi@sunmence.com",
    employeeRole: "Head of Marketing & Growth",
    department: "Marketing",
    bankName: "First Bank of Nigeria",
    accountNumber: "3091827364",
    accountName: "Grace Adeyemi",
    amount: 500000,
    fee: 50,
    netAmount: 500000,
    paymentType: "Salary",
    status: "pending",
    date: "2026-09-24T14:45:00",
    narration: "September Salary Disbursal",
  },
  {
    id: 5,
    reference: "PF-PAY-904125",
    batchId: "BATCH-2026-SEP-03",
    companyId: 103,
    companyName: "Global Logistics Inc",
    companyEmail: "billing@globallogistics.com",
    employeeName: "Chiamaka Eze",
    employeeEmail: "chiamaka.eze@globallogistics.com",
    employeeRole: "Fleet Operations Specialist",
    department: "Operations",
    bankName: "United Bank for Africa (UBA)",
    accountNumber: "2109876543",
    accountName: "Chiamaka Eze",
    amount: 320000,
    fee: 50,
    netAmount: 320000,
    paymentType: "Salary",
    status: "successful",
    date: "2026-09-23T16:10:00",
    narration: "Fleet Operations Monthly Payout",
    approvedBy: "System Auto-Disburse",
    approvedAt: "2026-09-23T16:12:00",
    gatewayRef: "UBA-TRF-102938475",
  },
  {
    id: 6,
    reference: "PF-PAY-904126",
    batchId: "BATCH-2026-SEP-03",
    companyId: 103,
    companyName: "Global Logistics Inc",
    companyEmail: "billing@globallogistics.com",
    employeeName: "Oluwaseun Adeleke",
    employeeEmail: "seun.adeleke@globallogistics.com",
    employeeRole: "Logistics Dispatch Supervisor",
    department: "Operations",
    bankName: "Kuda Microfinance Bank",
    accountNumber: "2001928374",
    accountName: "Oluwaseun Adeleke",
    amount: 180000,
    fee: 50,
    netAmount: 180000,
    paymentType: "Bonus",
    status: "successful",
    date: "2026-09-23T16:10:00",
    narration: "Q3 High Performer Operational Bonus",
    approvedBy: "System Auto-Disburse",
    approvedAt: "2026-09-23T16:12:00",
    gatewayRef: "KUD-TRF-491827364",
  },
  {
    id: 7,
    reference: "PF-PAY-904127",
    batchId: "BATCH-2026-SEP-04",
    companyId: 104,
    companyName: "Apex Health Systems",
    companyEmail: "accounts@apexhealth.ng",
    employeeName: "Dr. Fatima Bello",
    employeeEmail: "fatima.bello@apexhealth.ng",
    employeeRole: "Chief Medical Officer",
    department: "Clinical Care",
    bankName: "Zenith Bank",
    accountNumber: "1019283746",
    accountName: "Fatima Bello",
    amount: 1250000,
    fee: 50,
    netAmount: 1250000,
    paymentType: "Salary",
    status: "processing",
    date: "2026-09-24T15:30:00",
    narration: "Medical Consultants Monthly Retainer",
  },
  {
    id: 8,
    reference: "PF-PAY-904128",
    batchId: "BATCH-2026-SEP-04",
    companyId: 104,
    companyName: "Apex Health Systems",
    companyEmail: "accounts@apexhealth.ng",
    employeeName: "Emeka Okafor",
    employeeEmail: "emeka.okafor@apexhealth.ng",
    employeeRole: "Head of Laboratory Diagnostics",
    department: "Diagnostics",
    bankName: "Stanbic IBTC Bank",
    accountNumber: "0029384756",
    accountName: "Emeka Okafor",
    amount: 450000,
    fee: 50,
    netAmount: 450000,
    paymentType: "Allowance",
    status: "failed",
    date: "2026-09-23T09:15:00",
    narration: "Hazards & Clinical Equipment Allowance",
    rejectionReason: "Beneficiary bank account inactive or temporarily restricted by recipient institution (NIBSS 91: Inactive Account).",
  },
  {
    id: 9,
    reference: "PF-PAY-904129",
    batchId: "BATCH-2026-SEP-05",
    companyId: 105,
    companyName: "Sterling Retail Hub",
    companyEmail: "admin@sterlinghub.com",
    employeeName: "Ibrahim Mustapha",
    employeeEmail: "ibrahim.mustapha@sterlinghub.com",
    employeeRole: "Store Inventory Manager",
    department: "Inventory",
    bankName: "Wema Bank",
    accountNumber: "0239485716",
    accountName: "Ibrahim Mustapha",
    amount: 280000,
    fee: 50,
    netAmount: 280000,
    paymentType: "Salary",
    status: "successful",
    date: "2026-09-22T13:40:00",
    narration: "Store Team Monthly Salary",
    approvedBy: "Finance Clearance Desk",
    approvedAt: "2026-09-22T13:45:00",
    gatewayRef: "WEM-TRF-662910481",
  },
  {
    id: 10,
    reference: "PF-PAY-904130",
    batchId: "BATCH-2026-SEP-05",
    companyId: 105,
    companyName: "Sterling Retail Hub",
    companyEmail: "admin@sterlinghub.com",
    employeeName: "Blessing Johnson",
    employeeEmail: "blessing.johnson@sterlinghub.com",
    employeeRole: "Retail Sales Lead",
    department: "Sales",
    bankName: "Access Bank",
    accountNumber: "0691827364",
    accountName: "Blessing Johnson",
    amount: 150000,
    fee: 50,
    netAmount: 150000,
    paymentType: "Commission",
    status: "pending",
    date: "2026-09-24T16:00:00",
    narration: "August Sales Target Commission",
  },
  {
    id: 11,
    reference: "PF-PAY-904131",
    batchId: "BATCH-2026-SEP-06",
    companyId: 106,
    companyName: "Bluecrest Energy",
    companyEmail: "treasury@bluecrestenergy.com",
    employeeName: "Ken Nnamdi",
    employeeEmail: "ken.nnamdi@bluecrestenergy.com",
    employeeRole: "Petroleum Field Engineer",
    department: "Field Engineering",
    bankName: "Standard Chartered Bank",
    accountNumber: "5001928374",
    accountName: "Ken Nnamdi",
    amount: 1100000,
    fee: 50,
    netAmount: 1100000,
    paymentType: "Salary",
    status: "successful",
    date: "2026-09-21T08:30:00",
    narration: "Offshore Engineering Field Payout",
    approvedBy: "System Auto-Disburse",
    approvedAt: "2026-09-21T08:32:00",
    gatewayRef: "SCB-TRF-391827465",
  },
  {
    id: 12,
    reference: "PF-PAY-904132",
    batchId: "BATCH-2026-SEP-06",
    companyId: 106,
    companyName: "Bluecrest Energy",
    companyEmail: "treasury@bluecrestenergy.com",
    employeeName: "Halima Abubakar",
    employeeEmail: "halima.abubakar@bluecrestenergy.com",
    employeeRole: "Safety & Compliance Officer",
    department: "HSE Compliance",
    bankName: "Guaranty Trust Bank (GTBank)",
    accountNumber: "0182938475",
    accountName: "Halima Abubakar",
    amount: 350000,
    fee: 50,
    netAmount: 350000,
    paymentType: "Reimbursement",
    status: "successful",
    date: "2026-09-21T08:30:00",
    narration: "Offshore Safety Gear Reimbursement",
    approvedBy: "System Auto-Disburse",
    approvedAt: "2026-09-21T08:32:00",
    gatewayRef: "GTB-TRF-772918402",
  },
];

export const getInitialCompanyPayments = (): CompanyPaymentItem[] => [
  ...SEED_COMPANY_PAYMENTS,
];
